- name: Save compose file
  template: src=compose.j2 dest=/home/ubuntu/docker-compose.yml

- name: Deploy stack
  shell: "docker stack deploy --compose-file docker-compose.yml nginx"
  args:
    chdir: /home/ubuntu